#!/bin/sh -e
#-----------------------------------------------------------------------
# Parse a list of C prototypes extracted from PGPLOT files with the
# command "grep -h '^C%' pg*.f" to produce a listing of wrapper
# functions.
#
# Usage:
#  listfn [suffix]
#-----------------------------------------------------------------------
sed -e 's/ *(.*$/'$1'/g' -e 's/^.*[)\\].*$//g' -e 's/^ *C%.*cpg/cpg/g' < prototypes
